apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-agent.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
