apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-agent.labels" . | nindent 4 }}
  {{- with (dig "reader" "annotations" nil .Values.serviceAccount) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
